
package com.csgsystems.webservices.precisionemail._1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PrecisionEmailService", targetNamespace = "http://webservices.csgsystems.com/PrecisionEmail/1.0", wsdlLocation = "file:/C:/temp/precisionemail.wsdl")
public class PrecisionEmailService
    extends Service
{

    private final static URL PRECISIONEMAILSERVICE_WSDL_LOCATION;
    private final static WebServiceException PRECISIONEMAILSERVICE_EXCEPTION;
    private final static QName PRECISIONEMAILSERVICE_QNAME = new QName("http://webservices.csgsystems.com/PrecisionEmail/1.0", "PrecisionEmailService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/temp/precisionemail.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRECISIONEMAILSERVICE_WSDL_LOCATION = url;
        PRECISIONEMAILSERVICE_EXCEPTION = e;
    }

    public PrecisionEmailService() {
        super(__getWsdlLocation(), PRECISIONEMAILSERVICE_QNAME);
    }

    public PrecisionEmailService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRECISIONEMAILSERVICE_QNAME, features);
    }

    public PrecisionEmailService(URL wsdlLocation) {
        super(wsdlLocation, PRECISIONEMAILSERVICE_QNAME);
    }

    public PrecisionEmailService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRECISIONEMAILSERVICE_QNAME, features);
    }

    public PrecisionEmailService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PrecisionEmailService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PrecisionEmail
     */
    @WebEndpoint(name = "PrecisionEmailSoap11")
    public PrecisionEmail getPrecisionEmailSoap11() {
        return super.getPort(new QName("http://webservices.csgsystems.com/PrecisionEmail/1.0", "PrecisionEmailSoap11"), PrecisionEmail.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PrecisionEmail
     */
    @WebEndpoint(name = "PrecisionEmailSoap11")
    public PrecisionEmail getPrecisionEmailSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices.csgsystems.com/PrecisionEmail/1.0", "PrecisionEmailSoap11"), PrecisionEmail.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRECISIONEMAILSERVICE_EXCEPTION!= null) {
            throw PRECISIONEMAILSERVICE_EXCEPTION;
        }
        return PRECISIONEMAILSERVICE_WSDL_LOCATION;
    }

}
