
package com.csgsystems.webservices.precisionemail._1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PrecisionEmail", targetNamespace = "http://webservices.csgsystems.com/PrecisionEmail/1.0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PrecisionEmail {


    /**
     * 
     * @param sendBatchPrecisionEmailRequest
     * @return
     *     returns com.csgsystems.webservices.precisionemail._1.SendBatchPrecisionEmailResponseType
     */
    @WebMethod(operationName = "SendBatchPrecisionEmail")
    @WebResult(name = "SendBatchPrecisionEmailResponse", targetNamespace = "http://webservices.csgsystems.com/PrecisionEmail/1.0", partName = "SendBatchPrecisionEmailResponse")
    public SendBatchPrecisionEmailResponseType sendBatchPrecisionEmail(
        @WebParam(name = "SendBatchPrecisionEmailRequest", targetNamespace = "http://webservices.csgsystems.com/PrecisionEmail/1.0", partName = "SendBatchPrecisionEmailRequest")
        SendBatchPrecisionEmailRequestType sendBatchPrecisionEmailRequest);

    /**
     * 
     * @param sendTriggerBundlePrecisionEmailRequest
     * @return
     *     returns com.csgsystems.webservices.precisionemail._1.SendTriggerBundlePrecisionEmailResponseType
     */
    @WebMethod(operationName = "SendTriggerBundlePrecisionEmail")
    @WebResult(name = "SendTriggerBundlePrecisionEmailResponse", targetNamespace = "http://webservices.csgsystems.com/PrecisionEmail/1.0", partName = "SendTriggerBundlePrecisionEmailResponse")
    public SendTriggerBundlePrecisionEmailResponseType sendTriggerBundlePrecisionEmail(
        @WebParam(name = "SendTriggerBundlePrecisionEmailRequest", targetNamespace = "http://webservices.csgsystems.com/PrecisionEmail/1.0", partName = "SendTriggerBundlePrecisionEmailRequest")
        SendTriggerBundlePrecisionEmailRequestType sendTriggerBundlePrecisionEmailRequest);

    /**
     * 
     * @param retrieveEventsPrecisionEmailRequest
     * @return
     *     returns com.csgsystems.webservices.precisionemail._1.RetrieveEventsPrecisionEmailResponseType
     */
    @WebMethod(operationName = "RetrieveEventsPrecisionEmail")
    @WebResult(name = "RetrieveEventsPrecisionEmailResponse", targetNamespace = "http://webservices.csgsystems.com/PrecisionEmail/1.0", partName = "RetrieveEventsPrecisionEmailResponse")
    public RetrieveEventsPrecisionEmailResponseType retrieveEventsPrecisionEmail(
        @WebParam(name = "RetrieveEventsPrecisionEmailRequest", targetNamespace = "http://webservices.csgsystems.com/PrecisionEmail/1.0", partName = "RetrieveEventsPrecisionEmailRequest")
        RetrieveEventsPrecisionEmailRequestType retrieveEventsPrecisionEmailRequest);

    /**
     * 
     * @param sendTriggerPrecisionEmailRequest
     * @return
     *     returns com.csgsystems.webservices.precisionemail._1.SendTriggerPrecisionEmailResponseType
     */
    @WebMethod(operationName = "SendTriggerPrecisionEmail")
    @WebResult(name = "SendTriggerPrecisionEmailResponse", targetNamespace = "http://webservices.csgsystems.com/PrecisionEmail/1.0", partName = "SendTriggerPrecisionEmailResponse")
    public SendTriggerPrecisionEmailResponseType sendTriggerPrecisionEmail(
        @WebParam(name = "SendTriggerPrecisionEmailRequest", targetNamespace = "http://webservices.csgsystems.com/PrecisionEmail/1.0", partName = "SendTriggerPrecisionEmailRequest")
        SendTriggerPrecisionEmailRequestType sendTriggerPrecisionEmailRequest);

    /**
     * 
     * @param retrieveBatchStatusPrecisionEmailRequest
     * @return
     *     returns com.csgsystems.webservices.precisionemail._1.RetrieveBatchStatusPrecisionEmailResponseType
     */
    @WebMethod(operationName = "RetrieveBatchStatusPrecisionEmail")
    @WebResult(name = "RetrieveBatchStatusPrecisionEmailResponse", targetNamespace = "http://webservices.csgsystems.com/PrecisionEmail/1.0", partName = "RetrieveBatchStatusPrecisionEmailResponse")
    public RetrieveBatchStatusPrecisionEmailResponseType retrieveBatchStatusPrecisionEmail(
        @WebParam(name = "RetrieveBatchStatusPrecisionEmailRequest", targetNamespace = "http://webservices.csgsystems.com/PrecisionEmail/1.0", partName = "RetrieveBatchStatusPrecisionEmailRequest")
        RetrieveBatchStatusPrecisionEmailRequestType retrieveBatchStatusPrecisionEmailRequest);

}
